name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  application:
    name: Application Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies & Build Lambdas
        run: |
          for dir in application/*-lambda/; do
            if [ -f "$dir/package.json" ]; then
              echo "Processing $dir"
              cd "$dir"
              npm run prebuild
              npm run build
              npm run package
              npm run zip
              cd -
            fi
          done

      - name: List Packaged Files
        run: ls -lh application/dist/

  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    env:
      ENV: prod
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.3

      - name: Debug AWS Credentials
        run: env | grep AWS

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure

      - name: Terraform Validate
        run: terraform validate
        working-directory: infrastructure

      - name: Terraform Plan
        run: terraform plan -var="env=${ENV}" -out=tfplan
        working-directory: infrastructure

      - name: Terraform Apply (on Main Branch)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: infrastructure
